[local]

# Crear archivo etc/settings.toml completando los siguientes campos.

# GeoAPI settings
BASE_URL = "http://localhost:5000/"
TIMEZONE = "America/Buenos_Aires"
COORDINATE_SYSTEM = "EPSG:4326"
DEFAULT_CHUNKSIZE = 50

# Geoserver interface
GEOSERVER_BASE_URL = "http://localhost:8080/"
GEOSERVER_USERNAME = "username"
GEOSERVER_PASSWORD = "password"
GEOSERVER_WORKSPACE = "workspace"
GEOSERVER_DATASTORE = "datastore"

# PostGIS interface
POSTGIS_HOST = "localhost:5432"
POSTGIS_USER = "username"
POSTGIS_PASS = "password"
POSTGIS_DATABASE = "postgis"
POSTGIS_SCHEMA = "public"
POSTGIS_DRIVER = "postgresql+psycopg2"
