"""Migración inicial

Revision ID: 8c54fbb3ebc4
Revises: 
Create Date: 2023-08-12 21:36:11.210835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '8c54fbb3ebc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='geoapi'
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('obra', sa.String(), nullable=True),
    sa.Column('operatoria', sa.String(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('departamento', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('localidad', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('cantidad', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('ente', sa.String(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['geoapi.layers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='geoapi'
    )
    op.create_table('geometries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='GEOMETRYZ', srid=4326, dimension=3, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['geoapi.batches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='geoapi'
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('layer', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['geoapi.batches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='geoapi'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs', schema='geoapi')
    op.drop_table('geometries', schema='geoapi')
    op.drop_table('batches', schema='geoapi')
    op.drop_table('layers', schema='geoapi')
    # ### end Alembic commands ###
